CREATE TABLE CLUES_JAVA (
    ID VARCHAR(36) PRIMARY KEY,
    CATEGORY VARCHAR(100) NOT NULL,
    ROUND VARCHAR(2) NOT NULL,
    CATEGORY_NUMBER INT NOT NULL,
    VALUE VARCHAR(10) NOT NULL,
    QUESTION VARCHAR(1000) NOT NULL,
    ANSWER VARCHAR(100) NOT NULL,
    IS_DAILY_DOUBLE BOOLEAN NOT NULL,
    GAME_ID VARCHAR(10) NOT NULL,
    GAME_DATE VARCHAR(10) NOT NULL,
    DATE_ADDED VARCHAR(100) NOT NULL
);